### ISSUE TITLE
[TrainsDatabase] UI

### ISSUE THREAD

**Issue by pavel-b-novikov** [BelovEvgeny/nsudotnet#1]
* Скрыть все Id-колонки. Пользователь не должен их видеть
* Фильтрация. Там, где имеется ограниченное кол-во вариантов (роуты, поезда, станции) - сделать фильтрацию через .FilterSelectUi, списками
* Не показывать Id в таблицах (для поездов можно сделать исключение - там нет имен), а показывать имя везде, где это возможно

**Comment by BelovEvgeny** [comment]
Вроде все что нашел исправил.
